version: '2'
services:
  web:
    container_name: sales-app
    image: odoo:11    
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./src:/mnt/extra-addons
    environment:
          - DB_PORT_5432_TCP_ADDR=db
          - DB_PORT_5432_TCP_PORT=5432
          - DB_ENV_POSTGRES_USER=odoo
          - DB_ENV_POSTGRES_PASSWORD=odoo
  db:
    container_name: sales-db
    image: postgres:9.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo